/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResponseMetadata = IDL.Record({
  'model' : IDL.Text,
  'processingTimeMs' : IDL.Nat,
  'tokenEstimate' : IDL.Nat,
});
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
});
export const BotResponse = IDL.Record({
  'metadata' : ResponseMetadata,
  'message' : ChatMessage,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'getSuggestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [BotResponse], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResponseMetadata = IDL.Record({
    'model' : IDL.Text,
    'processingTimeMs' : IDL.Nat,
    'tokenEstimate' : IDL.Nat,
  });
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
  });
  const BotResponse = IDL.Record({
    'metadata' : ResponseMetadata,
    'message' : ChatMessage,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'getSuggestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text], [BotResponse], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };